DROP TABLE SF_MEMBER;
DROP TABLE SF_STUDY;
DROP TABLE SF_CHECK;
DROP TABLE SF_REPLY;
DROP TABLE SF_STUDYMEMBER;
DROP TABLE SF_FIELD;
DROP TABLE SF_LOC;

create sequence sf_study_seq;
create sequence sf_REPLY_seq;
create sequence sf_CHECK_seq;

CREATE TABLE SF_member
(
    USERID VARCHAR2(100) PRIMARY KEY,
    USERPWD VARCHAR2(100) NOT NULL,
    USEREMAIL VARCHAR2(100) NOT NULL,
    USER_ORIGINALFILENAME VARCHAR2(50),
    USER_SAVEDFILENAME VARCHAR2(50),
    FIELD_NO NUMBER REFERENCES SF_FIELD(FIELD_NO),
    LOC_NO NUMBER REFERENCES SF_LOC(LOC_NO),
    IMG VARCHAR2(200)
);
CREATE TABLE SF_STUDY
(
    STUDY_NO NUMBER PRIMARY KEY,
    Auth_USERID VARCHAR2(100) REFERENCES SF_member(USERID) ON DELETE CASCADE,
    STUDY_TITLE VARCHAR2(100),
    STUDY_CONTENT VARCHAR2(1000),
    FIELD_NO NUMBER REFERENCES SF_FIELD(FIELD_NO),
    LOC_NO NUMBER REFERENCES SF_LOC(LOC_NO),
    STUDY_LEVEL NUMBER,
    STUDY_HEADCOUNT NUMBER,
    STUDY_INPUTDATE DATE DEFAULT SYSDATE,
    study_hit number default 0,
    DUE_TIME VARCHAR2(50),
    PENALTY_MIN NUMBER,
    PENALTY_MONEY NUMBER,
    LIMIT_TIME VARCHAR2(50),
    PENALTY_TOTAL NUMBER DEFAULT 0
);

CREATE TABLE SF_CHECK(
    CHECK_NO NUMBER PRIMARY KEY,
    USERID VARCHAR2(100) REFERENCES SF_member(USERID),
    STUDY_NO NUMBER REFERENCES SF_STUDY(STUDY_NO),
    CHECKED NUMBER CHECK(CHECKED IN(1,0)),
    CHECK_INPUTDATE DATE DEFAULT SYSDATE,
    CHECK_PENALTY NUMBER DEFAULT 0
);

CREATE TABLE SF_REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    STUDY_NO NUMBER REFERENCES SF_STUDY(STUDY_NO),
    USERID VARCHAR2(100) REFERENCES SF_MEMBER(USERID),
    REPLY_TEXT VARCHAR2(1000),
    REPLY_INPUTDATE DATE DEFAULT SYSDATE,
    PERMISSION NUMBER default 0 CHECK(PERMISSION IN(1,0))
);

CREATE TABLE SF_STUDYMEMBER(
STUDY_NO NUMBER REFERENCES SF_STUDY(STUDY_NO),
PART_USERID REFERENCES SF_member(USERID),
AUTH_USERID REFERENCES SF_member(USERID)
);

CREATE TABLE SF_FIELD(
    FIELD_NO NUMBER PRIMARY KEY,
    FIELD_NAME VARCHAR2(20)
);
INSERT INTO SF_FIELD VALUES (1, '자격증');
INSERT INTO SF_FIELD VALUES (2, '고시');
INSERT INTO SF_FIELD VALUES (3, '출석');
INSERT INTO SF_FIELD VALUES (4, '취업');
INSERT INTO SF_FIELD VALUES (5, '기타');
COMMIT;

CREATE TABLE SF_LOC(
    LOC_NO NUMBER PRIMARY KEY,
    LOC_NAME VARCHAR2(20)
);
INSERT INTO SF_LOC VALUES(1, '서울');
INSERT INTO SF_LOC VALUES(2, '경기');
INSERT INTO SF_LOC VALUES(3, '경상');
INSERT INTO SF_LOC VALUES(4, '전라');
INSERT INTO SF_LOC VALUES(5, '제주');
COMMIT;